name: 'Replicate Github Release Asset'
description: 'Replicates a Github release to another repository'

inputs:
  repo:
    description: 'org/repo to download from'
    required: false
    default: ''
  version:
    description: 'version of the release to download from'
    required: false
    default: 'latest'
  file:
    description: 'name of the file in the release to download'
    required: true
  target:
    description: 'name of the target file path'
    required: false
  token:
    description: 'optional Personal Access Token to access external repository'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.version }}
    - ${{ inputs.file }}
    - ${{ inputs.target }}
    - ${{ inputs.token }}

outputs:
  version:
    description: 'The version of the release or tag'

branding:
  icon: 'download-cloud'
  color: 'blue'