include env.mk

test:
	GITHUB_REPOSITORY="none" \
	GITHUB_API_URL=$(GITHUB_API_URL) \
	INPUT_REPO=$(INPUT_REPO) \
	INPUT_VERSION=$(INPUT_VERSION) \
	INPUT_FILE=$(INPUT_FILE) \
	INPUT_TOKEN=$(INPUT_TOKEN) \
	INPUT_RELEASE_REPO=$(INPUT_RELEASE_REPO) \
	INPUT_RELEASE_VERSION=$(INPUT_RELEASE_VERSION) \
	INPUT_RELEASE_TARGET=$(INPUT_RELEASE_TARGET) \
	./run.sh